### ISSUE TITLE
CRL Study question (Filters in the Power density Loop point)

### ISSUE THREAD

**Issue by jureyherrera** [lucarebuffi/Paper_JSR_gy5009#1]
Dear Luca,

Thank you for sharing your ***.ows** of the paper calculations, very interesting study and quite useful new tools to obtain the power density from a complex beamline. Now, I have a doubt, in the case of the CRL study ([XPCS_SA_CRLs_10KeV_focus_at_PS](https://github.com/lucarebuffi/Paper_JSR_gy5009/blob/master/3.2_XPCS_beamline_power_calculation/XPCS_SA_CRLs_10KeV_focus_at_PS.ows)) I wonder why is necessary to include the reflectivity of the mirror:
![image](https://user-images.githubusercontent.com/31166917/94451377-98893c00-01ae-11eb-9835-d55e7830d0a4.png)

Because these contribution are already included in the corresponding M1 and M2 mirror widgets of the ray-tracing, e.g.:
![image](https://user-images.githubusercontent.com/31166917/94451605-e3a34f00-01ae-11eb-85b4-4ab6eae3c860.png)

And, if is not the case, why only one reflection is considered being that there are two absorptions due reflections on M1 and M2.

Finally, I guess the absorption due the Be CRL is negligible due the relatively high energy of the photon beam, and therefore not considered, is this right?

My apologies in advance if these questions are too naive, and I thank you for your consideration.
Kind regards,
Juan

**Comment by lucarebuffi** [comment]
1) "I wonder why is necessary to include the reflectivity of the mirror:". That is not the case. Including the reflectivity in the Looper widget  just allows the user to visualize and sample not the initial spectrum, but the spectrum actually "seen" by the thermally critical element. In the calculation, instead, it is Shadow doing the job, by calculating the effects of every optical element. Recently I added a more sophisticated widget call "Total Filter", that allow to calculate the "effective" spectrum even with a more complicated set (mirrors + filters + multilayers, etc.)

2) "Finally, I guess the absorption due the Be CRL is negligible due the relatively high energy of the photon beam, and therefore not considered, is this right?" Absolutely not, again, you need the optical parameters of Be to let Shadow compute the action of the CRLs. Then, it actually not true: worst case scenarios of accidental focusing on optical elements or radiation safety systems happens when focusing a low energy first harmonic (for XPCS ~11 KeV), where the effects of absorption are not negligible.

**Comment by jureyherrera** [comment]
Thanks a lot Luca, the fact that this feature is only for visualization purposes explains everything. Best regards, Juan

**Comment by lucarebuffi** [comment]
You're welcome, Juan. Glad you are interested in this new tools.
